POST http://admin.taichi.cool/auth/login
Content-Type: application/json

{"username":  "qnya","password": "qn12345"}
###

POST http://admin.taichi.cool/upload
Content-Type: multipart/form-data

--WebAppBoundary
Content-Disposition: form-data; name="file"

< C:\Users\Neuron\Downloads\Telegram Desktop\QNotified-release 0.8.10.182.bc1cee4.apk
--WebAppBoundary--